### ISSUE TITLE
spoof to 9.03

### ISSUE THREAD

**Issue by costelabr17** [GoldHEN/GoldHEN#14]
you can do a spoof to 9.03 on golden hen? Please

**Comment by Masamune3210** [comment]
Spoofing the version probably wont do what you think it does, it wont let you play later firmware games without a BP and it wont let you connect to PSN, which is a bad idea anyway since you would just get immediately banned

**Comment by SiSTR0** [comment]
what should be the advantage of having the 9.03 spoof?

**Comment by maree01** [comment]
can I use psvr on 9.00 without spoof?

**Comment by SiSTR0** [comment]
Unfortunately I don't have the psvr, it should work, but it seems that if you have the psvr updated with a higher version than the one supported by 9.0 it still doesn't work with other patches / spoofs either.
Anyway if you want to do some tests contact me on the OpenOrbis discord server

**Comment by cualquiercosa327** [comment]
> Unfortunately I don't have the psvr, it should work, but it seems that if you have the psvr updated with a higher version than the one supported by 9.0 it still doesn't work with other patches / spoofs either. Anyway if you want to do some tests contact me on the OpenOrbis discord server

Hello, first thanks for your awesome work.
I saw this while I was trying to make my new processor unit working with my old glass.
I am on 6.72 and it run without issues with GoldHEN.

Here is what it happened (i have seen toon of places asking how to solve but no solutions).


The issue is both proccesor unit and glasses need to have the same Fimware.
For that loading GoldHEN, activate Internet and update the psvr. Now the latest fw is 5.0.
Everything will work great.
Note : if i put the glass on with the OF, it will ask to update the ps4.Only cancel it. 
Using Golden zero issues.

Yours
