### ISSUE TITLE
GoldHEN_v2.4b17.2 > Issue in FTP

### ISSUE THREAD

**Issue by wasiq-diwan** [GoldHEN/GoldHEN#171]
After succesfull installation, when enabling Server Bitloader is successfull whereas the FTP doesn't work.

@SiSTR0, please advise

**Comment by Leandrollobo** [comment]
Hello! 
I'm trying to connect to the PS4 via FTP to transfer files.

I'm using the Raspberry Pi3 PPPwn method.
The PS4 gets my local IP, but when trying to connect via Filezilla it gives me 2 errors:
1- The connection expires after 20 seconds of inactivity.
2- Unable to connect to the server.

Is this a known bug for anyone using Raspberry Pi? 
Is there any alternative to connecting to the PS4 via FTP using the PPPwn method with a raspberry pi?

Thanks for the great work!

**Comment by samuelbirocchi** [comment]
Found this Reddit when searching for this issue. Apparently you have to enable the FTP server, reboot and JB the PS4 again for it to work

https://www.reddit.com/r/ps4homebrew/comments/1da2rus/ftp_server_not_working_1100_jb_goldhen_v24b17/

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18

**Comment by ITotalJustice** [comment]
> Hello! I'm trying to connect to the PS4 via FTP to transfer files.
> 
> I'm using the Raspberry Pi3 PPPwn method. The PS4 gets my local IP, but when trying to connect via Filezilla it gives me 2 errors: 1- The connection expires after 20 seconds of inactivity. 2- Unable to connect to the server.
> 
> Is this a known bug for anyone using Raspberry Pi? Is there any alternative to connecting to the PS4 via FTP using the PPPwn method with a raspberry pi?
> 
> Thanks for the great work!

Answering here in case anyone else has this same problem (when using pi for internet).

---

The IP you need to connect to your PS4 *whilst* it's using the pi for internet, is the IP of the pi, NOT the IP of the ps4. For example, the ps4 may report that it's IP is `192.168.2.2`, however you need to find out the IP of your pi and connect using that, such as `192.168.1.230` for example. Luckily, by default PI-Pwn sets the hostname of the pi to `pppwn.local`, meaning you can use it in-place of the IP address. So anywhere below where i mention to use the IP of the pi, use `pppwn.local` instead.

This causes a second issue with PASV (passive) mode. When a client issues a PASV command, it basically asks the ftp server to return the IP and port back to the client to be used for data transfers. The issue here is that the FTP server will return the PS4 ip (192.168.2.2), not the IP of the pi. And so the client tries to open the data connection, and eventually times out.

To work around this, you can use `active` mode (PORT command) to open the data connection instead.

---

## Filezilla

Open `Site manager`, create a new site, enter the name of it etc. On the right side, enter the IP of your pi in the `host` box, then set`Logon type` to `Anonymous`, then goto `transfer settings` and select `active` for transfer mode. Finally click `OK` at the bottom.

## UNIX ftp

Do `ftp ip port`. For example, `ftp 192.168.1.230 2121`. Then do `passive`. It should output `Passive mode off.`. Now you can do `ls` to ensure data transfers are working.

---

I made this comment a little more verbose that it needed to be, mainly because i wanted it to be useful for end users and to help the ftp server maintainers understand why it wasnt working for some users. It isn't your code thats broken 😄 I just spent a few hours auditing it myself as i assumed pasv was broken until i manually sent the pasv command and seen that it returned the IP of the ps4...which makes sense, obviously.
