### ISSUE TITLE
PS4 slim crashes when internet is connected and put into restmode

### ISSUE THREAD

**Issue by SaiMonicL** [GoldHEN/GoldHEN#205]
my PS4 slim crashes as soon as i connect my PS4 to the internet and then try to put it in restmode, is there any reason for this or is it just my PS4 that does it?

**Comment by Up-Zer0** [comment]
#187

**Comment by SaiMonicL** [comment]
but when i dont have any internet, it does go to rest mode 🤔

**Comment by KIMO-in** [comment]
You may have encountered that the device crashes when it is connected to the Internet, but the problem is actually in goldhen because it's still on beta phase

**Comment by IvoNexus** [comment]
The problem is not in the internet connection, but in the FTP server. First bug is when you disable the FTP server, then put in rest mode, after wake is again active. Since we know this, sometimes(2-3 times) FTP server causing kernal panic, now this could be from many factors, network interface not ready, his service got corrupted from properly shutdown or etc. So yeah GOLDHEN works perfectly aside from that. I'm using it on PS4 Slim 10.01 with SSD.

**Comment by Flaguun** [comment]
On my PS4 Pro the FTP is unchecked and it's a 0 in the config file. Still crashing.

**Comment by jason-eu** [comment]
> my PS4 slim crashes as soon as i connect my PS4 to the internet and then try to put it in restmode, is there any reason for this or is it just my PS4 that does it?

I discovered the same as @IvoNexus and wrote couple things about it.

Check issue #209 and see the effect [here](https://www.youtube.com/playlist?list=PL6R1p2LScl08suhyUWhn1A5EZ0M7hwgE8).

**Comment by IvoNexus** [comment]
> On my PS4 Pro the FTP is unchecked and it's a 0 in the config file. Still crashing.

Check if BinLoader server is active as well and shut it down, I haven't wrote about it because I just don't need it. Got no issues, like on my 20 wake since my last update, I haven't reboot it yet, works fine.

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
