### ISSUE TITLE
672 goldhen2.1 crashes

### ISSUE THREAD

**Issue by wutao981128464** [GoldHEN/GoldHEN#23]
Ps4Pro 7218B(firmware 6.72)  crash when loading goldhen2.1 in 2 conditions:1.crashed immediately  when the step of exploit 2. crashed when reboot because exploited failed remind 'jailbreak failed,reboot your ps4 and try again‘’.The probabiity of crash is 1 in 6. But nothing happened when loading goldhen1.1.no crashes even when 'jailbreak failed,reboot your ps4 and try again‘’. hope improve the stability of goldhen 2.1 6.72 bin,thanks  your team for everything contributed.

**Comment by SiSTR0** [comment]
from what you say the crashes happen in an embedded version of the payload with the exploit. it could be that the embedding was not done well. My suggestion to see if the crash is due to the payload is to run the bin directly and not use embedded versions.
I have personally tested 6.71 / 2 via exploit binloader and have never crashed.

**Comment by wutao981128464** [comment]
i'll try it and then report ,thanks a lot.

**Comment by wutao981128464** [comment]
whose  "exploit binloader" is good?

**Comment by wutao981128464** [comment]
how about the karo's exploit binloader?i find one.

**Comment by wutao981128464** [comment]
can u give me ur test " exploit binloader" ,thanks.

**Comment by wutao981128464** [comment]
thanks
