### ISSUE TITLE
FPKG DLCS get deleted from external storage After Fixing external hard disk

### ISSUE THREAD

**Issue by Scalerize** [GoldHEN/GoldHEN#67]
This issue only Affects FPKG DLCS that are Stored on the External storage,

Sometimes External storage gets corrupted either by turning off ps4 incorrectly or a Kernel panic occurs, which makes it necessary for the ps4 to fix the storage,
 but the thing is that after fixing the external storage before enabling goldhen, i find out that Some dlcs just magically Disappear, But when fixing the storage while goldhen is loaded, the dlcs are fully restored, The issue is not about Data corruption since Fpkg Game and Patch do not dissapear, only DLCS from FPKGS, Only workaround right now is plugging in external hard disk after enabling goldhen after an unexpected shutdown, or removing and plugging the hard disk from menu after enabling goldhen.

**Comment by RandQalan** [comment]
Fyi after loading Golden Hen disconnect usb Hdd and reconnect it afterwards it should recognize dlc on ext HDD.

**Comment by Scalerize** [comment]
> Fyi after loading Golden Hen disconnect usb Hdd and reconnect it afterwards it should recognize dlc on ext HDD.

OMG that fixed it thank you so much man!, But regardless i hope SISTR0 does something about this instead of having to do this workaround!

**Comment by RandQalan** [comment]
This problem never be truly be fixed because of  pfs encryption.

**Comment by remlei** [comment]
this is more like a standard ps4 checks when hacks is not loaded in memory, of course any fpkg will probably not register to PS4 because it only accepts sony signed packages. 

what I recommend if you get a kernel panic with extended storage in use (or plugged in), as soon as it asked you to repair the extended storage, just choose cancel and then enable goldhen, once its jailbreaked, you can do the extended storage repair by going to settings >> devices >> usb storage and choose use extended storage. 

If you accidentally proceed with extended storage repair, thats fine, just go to settings, devices >> usb storage and choose stop using extended storage. enable goldhen, after that go back to device>>usb storage again and choose use extended storage.

**Comment by kmeps4** [comment]
Not GoldHEN issue. Closed
