### ISSUE TITLE
Orbis Toolbox v2.0 Issues under GoldHEN 2.2.5b2

### ISSUE THREAD

**Issue by muxi1** [GoldHEN/GoldHEN#84]
The following problems with Orbis Toolbox v2.0 under GoldHEN 2.2.5b2 were mentioned to me by a member of my forum:

"The hooks are no longer displayed what is active in the toolbox. The temperature is no longer displayed. And after sleep mode, the Gold HEN is no longer loaded in the system settings and therefore the cheat menu then no longer opens properly."

On the other hand, these problems do not exist under GoldHEN version 2.2.4. Whether there is a need for action regarding GoldHEN 2.25b2 or the Toolbox, I cannot judge.

**Comment by kmeps4** [comment]
Hello.
Thx for the report!!! I'll try to reproduce and after will give you an answer.
--Kme---

**Comment by maxandroid** [comment]
Will there be an option to load the processor and temperature in goldhen?

**Comment by kmeps4** [comment]
I can confirm some issues on v2.2.5b2 & ToolBox v2.
we're checking a proper solution on this.
Thx for the report.

**Comment by BestDeveloper007** [comment]
I don't know if this problem is also in version 2.1.2(probably yes), but would it be possible to verify and keep alive a "lightweight" version like 2.1.2? I mean adding only some fixes without the Cheat menu and only with the most important... With 2.5.5b7 lags can be seen in the entire system and it also takes a long time to save games etc...
On the contrary, version 2.1.2 is fast and lag-free. Of course, the Cheats menu is a wonderful thing, but I don't always need it, and when I do, I have the choice of loading the light or heavy version of GoldHen. 

A lot of people are using version 2.1.2 and if they want to play with Cheats (or other special functions) then just turn on heavy version :) Thanks for at least thinking about it

**Comment by kmeps4** [comment]
Main bug report has been fixed on GoldHEN 2.3.
